import 'server-only'
import type { KnowledgeEntryWithRelations } from '@/modules/knowledge/types/knowledge.types'

export function renderSkillMd(entry: KnowledgeEntryWithRelations): string {
  const lines: string[] = [
    `# ${entry.title}`,
    '',
    entry.summary,
  ]

  if (entry.problem) {
    lines.push('', '## Problem', '', entry.problem)
  }

  if (entry.explanation) {
    const stripped = entry.explanation.replace(/<[^>]*>/g, '')
    lines.push('', '## Explanation', '', stripped)
  }

  if ((entry.bestPractices as string[]).length > 0) {
    lines.push('', '## Best Practices', '')
    ;(entry.bestPractices as string[]).forEach((p) => lines.push(`- ${p}`))
  }

  if ((entry.antiPatterns as string[]).length > 0) {
    lines.push('', '## Anti-Patterns', '')
    ;(entry.antiPatterns as string[]).forEach((p) => lines.push(`- ❌ ${p}`))
  }

  if ((entry.relatedConcepts as string[]).length > 0) {
    lines.push('', '## Related Concepts', '')
    ;(entry.relatedConcepts as string[]).forEach((c) => lines.push(`- ${c}`))
  }

  return lines.join('\n')
}

export function renderClaudeMd(entries: KnowledgeEntryWithRelations[]): string {
  const lines: string[] = [
    '# Engineering Context Pack',
    '',
    '> Generated by PractiCode. These are the engineering rules and best practices for this project.',
    '',
  ]

  for (const entry of entries) {
    lines.push(`## ${entry.title}`, '')
    lines.push(entry.summary, '')

    if ((entry.bestPractices as string[]).length > 0) {
      lines.push('**Best Practices:**')
      ;(entry.bestPractices as string[]).forEach((p) => lines.push(`- ${p}`))
      lines.push('')
    }

    if ((entry.antiPatterns as string[]).length > 0) {
      lines.push('**Avoid:**')
      ;(entry.antiPatterns as string[]).forEach((p) => lines.push(`- ${p}`))
      lines.push('')
    }

    lines.push('---', '')
  }

  return lines.join('\n')
}

export function renderCopilotInstructions(entries: KnowledgeEntryWithRelations[]): string {
  const lines: string[] = [
    '# Copilot Instructions',
    '',
    'Follow these engineering best practices when generating code for this project:',
    '',
  ]

  for (const entry of entries) {
    lines.push(`## ${entry.title}`)
    if ((entry.bestPractices as string[]).length > 0) {
      ;(entry.bestPractices as string[]).forEach((p) => lines.push(`- ${p}`))
    }
    lines.push('')
  }

  if (entries.some((e) => (e.antiPatterns as string[]).length > 0)) {
    lines.push('## Patterns to avoid', '')
    for (const entry of entries) {
      ;(entry.antiPatterns as string[]).forEach((p) => lines.push(`- ${p}`))
    }
  }

  return lines.join('\n')
}
